name: production

services:
  chroniq-postgres:
    restart: unless-stopped
    image: postgres
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: chroniq
    volumes:
      - pgdata:/var/lib/postgresql/data
  chroniq:
    restart: unless-stopped
    image: chroniq
    ports:
      - "8080:8080"
    depends_on:
      - chroniq-postgres
volumes:
  pgdata: