name: ci

on: [push]

jobs:
  log:
    runs-on: ubuntu-latest
    steps:
      - name: Log
        run: echo "Hello World"

      - name: checkout
        uses: actions/checkout@v4

      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: latest

      - name: log node version
        run: node --version
