name: ci

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Log
        run: echo "Hello World"

      - name: checkout
        uses: actions/checkout@v4

      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: latest

      - name: change dir
        run: cd src/Chroniq.WebClient

      - name: ls
        run: ls

      - name: log node version
        run: node --version

      - name: install deps
        run: npm install

      - name: lint
        run: npm run lint
