name: ci

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: latest

      - name: Debug with tmate
        uses: mxschmitt/action-tmate@v3

      - name: install deps
        run: npm install

      - name: lint
        run: npm run lint
        working-directory: ./src/Chroniq.WebClient
