name: Builder Docker Image

on:
  push:
    branches: ["main"]

# on:
#   workflow_run:
#     workflows: ["ESLint", "Run ReSharper CleanupCode"]
#     types:
#       - completed
#

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t mEzdpg2kLJ9nAg/chroniq:latest .
        working-directory: ./src

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Push Docker image
        run: docker push mEzdpg2kLJ9nAg/chroniq
